### ISSUE TITLE
Enabled Bucket Broken 

### ISSUE THREAD

**Issue by BeastDD** [filliptm/ComfyUI_FL-Trainer#11]
Hello,

I would love to give a try to this extension unfortunately I cannot. Every single time I try to run the easy trainer or the advanced one I get an error about my tensors being of different size when its expected from them to all be the same size. However enabled bucket is on. 

So far the only way to fix this is to resize every single images to the exact same size but it defeats the purpose of having buckets enabled. I know you're probably super busy so I am fine waiting for a fix for this but I’d just thought Id let you know.

 I really want to get back into Lora Training and this is keeping me from it right now. My data sets have too many images, it’s bad enough I spend hours on the perfect captions, I really don't want to sink extra time into resizing each images 🙈.

**Comment by filliptm** [comment]
yes, this is a known issue, def going to work on this! I also am going to add a few GPT vision nodes that allow for Fast accurate captioning based on your prompt to it.

**Comment by filliptm** [comment]
issue fixed, please update
