### ISSUE TITLE
.nodes.FL_LoadImagesFromDirectoryPath in init_py caused failure.

### ISSUE THREAD

**Issue by ginnyliou** [filliptm/ComfyUI_FL-Trainer#12]
Hi, just want to raise this issue.

https://github.com/filliptm/ComfyUI_FL-Trainer/blob/8a032381ef46b46a1b306ae2c92f05f6257ea9c8/__init__.py#L8

![image](https://github.com/user-attachments/assets/c843bdd2-f5df-472b-89dc-f3e34ee47abb)

Current workaround is to remove the .nodes and restart comfyui so the nodes can be loaded.

**Comment by filliptm** [comment]
thanks, fixed
